# Generated by Django 5.2.4 on 2025-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], default='password_reset', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
