# Generated by Django 5.2.4 on 2025-08-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_optimize_conversation_ordering'),
        ('chat', '0004_populate_group_memberships'),
    ]

    operations = [
    ]
