# Generated by Django 5.2.4 on 2025-08-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresponse',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='eventresponse',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='child_name',
        ),
    ]
