# Generated by Django 5.2.4 on 2025-07-30 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyavailability',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='monthlyavailability',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useravailability',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Availability', 'verbose_name_plural': 'User Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='useravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='afternoon_available',
            field=models.BooleanField(default=False, help_text='12:00-17:00'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='current_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='evening_available',
            field=models.BooleanField(default=False, help_text='17:00-20:00'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='morning_available',
            field=models.BooleanField(default=False, help_text='8:00-12:00'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='night_available',
            field=models.BooleanField(default=False, help_text='20:00-22:00'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='selected_days',
            field=models.JSONField(default=list, help_text='Selected days as array [0,1,2,3,4,5,6] where 0=Sunday'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AvailabilityStatus',
        ),
        migrations.DeleteModel(
            name='MonthlyAvailability',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='time_slots',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
