# Generated by Django 5.2.4 on 2025-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_alter_monthlyavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravailability',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='selected_days',
        ),
        migrations.AddField(
            model_name='useravailability',
            name='afternoon_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', help_text='Afternoon 12:00-17:00 availability status', max_length=20),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='evening_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', help_text='Evening 17:00-20:00 availability status', max_length=20),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='morning_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', help_text='Morning 8:00-12:00 availability status', max_length=20),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='night_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', help_text='Night 20:00-22:00 availability status', max_length=20),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='afternoon_available',
            field=models.BooleanField(default=False, help_text='Is afternoon slot enabled'),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='evening_available',
            field=models.BooleanField(default=False, help_text='Is evening slot enabled'),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='morning_available',
            field=models.BooleanField(default=False, help_text='Is morning slot enabled'),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='night_available',
            field=models.BooleanField(default=False, help_text='Is night slot enabled'),
        ),
    ]
