# Generated by Django 5.2.4 on 2025-07-30 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_remove_useravailability_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], help_text='Which time slot this availability applies to', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maybe', 'Maybe')], default='available', help_text='Availability status for this time slot', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Is this time slot available for playdates')),
                ('repeat_schedule', models.CharField(choices=[('once', 'Just this once'), ('weekly', 'Repeat weekly'), ('monthly', 'Repeat monthly')], default='once', help_text='How often this time slot availability repeats', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Slot Availability',
                'verbose_name_plural': 'Time Slot Availabilities',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slot_type', 'start_date')},
            },
        ),
    ]
