# Generated by Django 5.2.4 on 2025-07-30 08:15

import calender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_timeslotavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotavailability',
            name='start_date',
            field=models.DateField(default=calender.models.get_today),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='start_date',
            field=models.DateField(default=calender.models.get_today),
        ),
    ]
